### ISSUE TITLE
Error querying with BlueIris 5.x

### ISSUE THREAD

**Issue by csteenwyk** [fahrer16/udi-blue-iris-poly#5]
This was working great with BI 4.x, upgraded to 5.x with stunnel and now I get this constantly:

`2019-06-22 00:40:28,401 [Controller] [DEBUG] Initializing Blue Iris Connection, session: 567905014a86216e178e714b57a16914
2019-06-22 00:40:28,403 [Controller] [INFO ] Connected to ...
2019-06-22 00:40:28,437 [Controller] [INFO ] Connecting to Blue Iris host ...
2019-06-22 00:40:28,511 [Controller] [DEBUG] Initializing Blue Iris Connection, session: 6ca93e6261cb71797b426d4e62156a7c
2019-06-22 00:40:28,512 [Controller] [INFO ] Connected to ...
2019-06-22 00:40:28,547 [Controller] [ERROR] Error querying Blue Iris Blue Iris`

**Comment by DaveStLou** [comment]
I am getting the same error after upgrading from 4.x to 5.x without stunnel.

Response when I opened ticket with Blue Iris support:

> Something is connecting to your Blue Iris server but when it connects again it is not sending the session key back.  This needs to be included in a cookie (usually automatic) or you can add it to the URL with &session=X if you are the one doing the scripting.

**Comment by therealmysteryman** [comment]
I have also the same issue

**Comment by therealmysteryman** [comment]
Looking at the documentation the API have changed and would required some change.

**Comment by csteenwyk** [comment]
I am working on a potential fix. I don't understand what the "remote" value should be for the status command. I think that is my last holdup. I e-mailed BlueIris for information

**Comment by fahrer16** [comment]
Corrected with v1.3.0.  The "cmd" function was passing the response parameter with each command.  This was never needed for v4 but it didn't seem to have a problem with it.  In v5, this resulted in every command failing.
