### ISSUE TITLE
Polyglot connection status always shows as false

### ISSUE THREAD

**Issue by DaveStLou** [fahrer16/udi-blue-iris-poly#7]
The NodeServer online status always shows as false in the ISY administrative console.
In blue-iris-poly.py I found it can be fixed by changing value in line 191,
from:     drivers = [{'driver': 'ST', 'value': **0**, 'uom': 2}, #Polyglot connection status
to:     drivers = [{'driver': 'ST', 'value': **1**, 'uom': 2}, #Polyglot connection status

**Comment by fahrer16** [comment]
Updated in version 1.3.1.  I wish I had seen this before doing the update, would've saved me some time digging into the cause!
